language: node_js
node_js:
  - "4.0"
env:
  global:
    secure: "TC2xJEnIFnUed03DQXhqFW8uyxDk++1Hw1PUpzUcmRuGuuLHVDJFOZgvPAICN3fD6fKLb8X6pRHHiXgoGD5nyhdoyY45tEJ1DaXHmHxtJ/3G/lOVKnQtPmkAkrvMJFxZWgIlJmXvJAuRPt4ow3lH/QXjKiIR5p3FBn4nevGGEU+qAUogCn13KEOxdjupzorWbV4oFURpH7Qi8sWS/bAGYM8aDmby2I4yAOv4KpyVixzt1t+Mll/TBeuqTaOcz/pZ4XDuN1NiUzLDN0qm295c+4YCiCB1ep5BLuYlG1RhKhCg6Nve7/VWgXISOXzdCprmYZPegWbLysrMInSgHM3ZJdCOJrNeE5DJWuFfytCJz6OyHzW7wz1CDYLDyOvyt+e0XplwgKlyT8QJs9q04ErbROcFZL2cQgGW86R3+YYXTyyAQlUBcUwxKbcHBdtPHCPMAOo6ILknpRom4gUS4vh0E2e01Dgvfw2ZeGMbVrzBPm0llbKLJOGjAtslmJHADqR8AV+sjzX3xZYev/m78RHyHogc/vTY7I3B4jwGwq7FTFHJiI1BK5RSOKSPWGmQ4KDJuyE4NzZ8z1YvFKIH7QdMvZYLSjhmPBtAJBhgo9MrCA6d59odJrkXRVsnZu2WtTElsFWYow/sh7gh32ufvP3goGcBvJwpYyhUFLA0OMyTVTc="
cache:
  directories:
  - $HOME/calibre-bin
sudo: false
before_script:
  - export PATH=$PATH:$HOME/calibre-bin/calibre
  - >
    which calibre ||
    wget -nv -O- https://raw.githubusercontent.com/kovidgoyal/calibre/master/setup/linux-installer.py |
    python -c "import sys; main=lambda x,y:sys.stderr.write('Download failed\n'); exec(sys.stdin.read()); main('~/calibre-bin', True)"
script:
  - npm run archive
after_success:
  - ./.ci/update-gh-pages.sh > /dev/null 2>&1
notifications:
  email:
    on_success: never
    on_failure: never
